In [2]:
import numpy as np

# Define the control points
control_points_wgs84 = np.array([[54.334902231, 9.690083758, 55.714807333],
                                [54.334965665, 9.686003336, 56.243414101],
                                [54.338624714, 9.684074937, 54.126570882],
                                [54.335072284, 9.696186240, 56.616201350],
                                [54.337859957, 9.697067333, 58.663761530],
                                [54.338206339, 9.694278547, 57.763711316]])

control_points_cartesian = np.array([[6022967.58100, 3544954.66400, 13.67700],
                                     [6022972.05400, 3544689.17800, 14.19800],
                                     [6023378.13700, 3544559.79500, 12.09100],
                                     [6022990.42000, 3545351.42900, 14.54200],
                                     [6023301.27500, 3545405.66800, 16.59400],
                                     [6023338.02800, 3545223.91000, 15.68400]])

# Define a function to calculate the transformation matrix
def calculate_transformation_matrix(control_points_wgs84, control_points_cartesian):
    # Add a column of 1s to the control points in WGS84 coordinates
    ones_column = np.ones((len(control_points_wgs84), 1))
    control_points_wgs84_ones = np.hstack((control_points_wgs84, ones_column))

    # Calculate the transformation matrix using least squares
    transformation_matrix, residuals, rank, s = np.linalg.lstsq(control_points_wgs84_ones, control_points_cartesian, rcond=None)

    return transformation_matrix

# Calculate the transformation matrix
transformation_matrix = calculate_transformation_matrix(control_points_wgs84, control_points_cartesian)

# Print the transformation matrix
print(transformation_matrix)




[[ 1.11312632e+05 -1.08699624e+03 -1.75518189e+00]
 [ 6.38157793e+02  6.50473610e+04 -2.42858052e+00]
 [-7.15469388e-03 -1.64863275e-02  9.97109806e-01]
 [-3.13767856e+04  2.97370305e+06  7.70129652e+01]]


In [3]:
# Define a point in WGS84 coordinates
def transform(wgs84_point):
    point_wgs84 = wgs84_point

    # Add a 1 to the end of the point
    point_wgs84_1 = np.hstack((point_wgs84, 1))
    point_wgs84_1 = point_wgs84_1

    # Multiply the point by the transformation matrix to get the point in cartesian coordinates
    point_cartesian = np.dot(point_wgs84_1, transformation_matrix)

     # Round each coordinate to 3 decimal points
    point_cartesian_rounded = [round(x, 3) for x in point_cartesian]

    # Print the point in cartesian coordinates with 3 decimal points
    print(point_cartesian_rounded)


In [4]:
transform([53.495680, 9.926153, 48.823])

[5929702.258, 3561222.699, 7.694]
